---
title: "Exploratory Analysis"
output: html_document
---

## Project title

Project Studious Student Performances

### Authors

Thi Trang, Vanessa Kanam, Audrey Phan

### Date

May 17th, 2024

### Abstract

Our main question is how factors like gender, ethnicity, parental education, and whether they have reduced lunch influences student test scores and study habits. This question is important because understanding these impacts can guide more effective educational interventions. To address this question, we will analyze a dataset of 1,000 students from Kaggle, using statistical methods and machine learning models, as
well as create charts to analyze data from our dataset.

### Keywords

Student study performance, socio-demographic factors, test scores, race and ethnicity.

### Introduction  

Academic performance serves as a way to help students develop life skills, advance career choices, and to build confidence. It is important as we have a learning level to meet but to do so we have different factors on meeting academic expectations. There are always more room to make more strategies to improve academic performance and reduce academic risks. Moreover, there has been studies how academic performance can be linked to physical fitness, with understanding the correlation between the two. Understanding the factors that influence academic performance is essential for educational research. Our project explores and highlights the relationship between various subjects including gender, sex, ethnicity, race, family background education, as well as if eating lunch with those who have standard or free and reduced lunch can be affected by student’s performance in school. It leads to questions such as does parental level education affect their student to learn better? Which race or ethnicity has lower and higher test scores? Does gender and sex play a role on who performs better? All these subjects will reflect the data in groups on how students perform in math, writing, and reading. Analyzing these student performance factors can help identify and improve education programs as well to have a greater impact on their success.

### Related Work  

The topic we chose was Student Study Performances. Related works we found with this topic is from Watermark Insights, called "You Say Tomato, I say Tomato: Are Student Performance and Student Learning Outcomes the Same Thing?" which explains the difference between student performances and learning outcomes. Performance outcomes are results an institution wants to see from students, while student learning outcomes are things like being able to communicate well, applying your learning to experiences, etc.. The second is a research article from Frontiers called "Student performance in online learning higher education: A preliminary research" which analyzes the impact of student performance in online learning experiences. This study includes different sections such as e-learning technology, student satisfaction, and student performance impact parts, which go in depth. Lastly, the last relevant work chosen was from the Wisconsin Department of Public Institution, which shows different levels of student performances. They created a standard setting which is linked on the website in order to gauge the academic standards. They separate performance levels into four categories: advanced, proficient, basic, and below basic. We chose this article especially because it is government officiated which shows the way some states have as their standard for gauging performance levels in students, which could potentially be helpful in our study later on when we look at student study performances.

Sources:

1. Prabowo, Hartiwi, et al. “Student Performance in Online Learning Higher Education: A Preliminary Research.” Frontiers, Frontiers, 22 Sept. 2022, www.frontiersin.org/articles/10.3389/feduc.2022.916721/full.

2. Watermark Insights. “You Say Tomato, I Say Tomato: Are Student Performance and     Student Learning Outcomes the Same Thing?” Watermark Insights, 26 Feb. 2024, www.watermarkinsights.com/resources/blog/you-say-tomato-i-say-tomato-are-student-performance-and-student-learning-outcomes-the-same-thing.

3. Wisconsin Department of Public Institution. “Student Performance Levels.” Wisconsin Department of Public Institution, dpi.wi.gov/sites/default/files/imce/assessment/pdf/Student_Performance_Levels.pdf. Accessed 2 May 2024.

### The Dataset

This dataset comes from Kaggle, a website where data scientists share work on data to build machine learning models. The dataset was collected by Bhavik Jikadara, a Data Scientist known for his proficiency to use Machine Learning, Natural Language Processing, and Deep Learning. There are 1,000 observations and 8 features in this dataset, including gender, race/ethnicity, parental level of education, lunch, test preparation course, scores in math, reading, and writing. The purpose behind this data was likely to analyze and understand how different factors can affect student performances, which can aid in educational planning and tailor the teaching style more appropriately to accommodate the needs of students.

When analyzing this data, it’s crucial to maintain ethical standards, especially when the data might involve information about students that are under the age of 18; ensuring the anonymity and privacy of the students’ data is essential to prevent any potential misuse. Additionally, it’s important to consider whether the dataset fairly represents different populations or if there’s any bias in the way the data was collected.

There are several limitations to this dataset which include its cope being too narrow (only a 1000 observations) to generalize across different educational systems or cultural contexts. Thus, there is a higher risk of bias information being involved in the absence of some factors. Second, the data collection methods aren’t transparent, so it is unknown where and when the data was being collected. These aspects are critical to consider, ensuring that all conclusions are liable and relevant to use.

### Implications

There are many significant factors that can get in the way of academic performance. One of the research questions we plan to answer, does parental level education affect their student to learn better? Parent education is an important index of social economic status, as it can predict children’s educational, cognitive outcomes. There has been a relation between poverty and low social economic status which can lead to negative child outcomes such as low IQ, more social problems. Having a lower socioeconomic status can give people the disadvantage. Students who live in poverty often have fewer resources either in school, at home, etc. Those with parent education can be linked directly with the child developing academic success and achievement attitudes. In general, social learning is shaped by observation and learning experiences. If a child is exposed to parents who modeled achievement behavior will often guide their children that achievement is valued.

### Limitations & Challenges

Student study performances is a broad topic, because there are many different ways a student can show their performances, many types of students, and study methods, all which can affect the data set and how to interpret and analyze it. The data set we chose has a lot of factors they put down, some which can be noted as a correlation, such as parental level of education and whether the students have free/reduced lunch. A challenge relating to this could be finding relationships between the sections in this dataset without assuming they cause the other, because correlation does not equal causation. Another limitation could be that the related works we may find probably come from a variety of sources, some which could be biased or skewed, so it will be important in our study to use accurate sources. Another challenge we may run into is comparing data between, for example, an area with a more prestigous education system versus a less one, and we will have to rule out these outliers when completing our study.

### Summary Information


### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
